# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [ ]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix



## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [ ]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [ ]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v



## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [ ]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



# RESPUESTAS
## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.
### Rta:
H es una matriz hermitian y sus eigenvalues son : $$ Eigenvalues= \begin{bmatrix} 4.44948974 & -6.70989255e-17i \\-0.44948974 & +1.15877743e-17i \end{bmatrix} $$

In [ ]:
import numpy as np
# Hermitian matrix
hermitian_matrix = np.array([[3+0j, 2+1j], [2-1j, 1+0j]])
# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)
import numpy as np
# eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(hermitian_matrix)

print("Eigenvalues:", eigenvalues)

is_hermitian, hermitian_matrix

Eigenvalues: [ 4.44948974-5.06745162e-17j -0.44948974+5.06745162e-17j]


(True,
 array([[3.+0.j, 2.+1.j],
        [2.-1.j, 1.+0.j]]))

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.
### Rta:
U es una matriz unitaria y $$ UU^\dagger =0i $$

In [3]:
# La matriz unitaria compleja que nos dan 
unitary_matrix = np.array([[1/np.sqrt(2)+0j, 1/np.sqrt(2)*1j], [1/np.sqrt(2)*1j, 1/np.sqrt(2)+0j]])

# Verificamos que la matriz sea unitaria
# np.eye(2) devuelve la identidad de3 tamaño 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

adjunct_unitary_matrix = unitary_matrix.T.conj()
complex_internal_product_matrix = np.trace(np.dot(np.conjugate(unitary_matrix).T, adjunct_unitary_matrix))

is_unitary, unitary_matrix,complex_internal_product_matrix

(True,
 array([[0.70710678+0.j        , 0.        +0.70710678j],
        [0.        +0.70710678j, 0.70710678+0.j        ]]),
 0j)

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:
$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$
Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.
### Rta
El producto tensor es: $$ \mathbf{v} \otimes \mathbf{w}  =  \begin{bmatrix} 3-i & 3+3i \\ -5i & 6-3i \end{bmatrix}$$

In [4]:

import numpy as np

# Defino los dos vectores complejos a usar
v1 = np.array([1+1j, 2-1j])
v2 = np.array([1-2j, 3])

# Calcula el producto tensor
tensor_product_v = np.kron(v1, v2)

tensor_product_v

array([3.-1.j, 3.+3.j, 0.-5.j, 6.-3.j])

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.
### Rta
El producto tensor  es: $$ \mathbf{v} \otimes \mathbf{w}  =  \begin{bmatrix} 0 & 0 & i & 0 \\ 0 & 0 & 0 & -i \\ i & 0 & 0 & 0 \\ 0 & -i & 0 & 0\end{bmatrix}$$

In [5]:

# Defino las matrices a usar 
M1 = np.array([[0, 1], [1, 0]])
M2 = np.array([[1j, 0], [0, -1j]])

# Calculo el producto tensor
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j]])

## Ejercicio 5: Modelado de Cálculos Cuánticos con Vectores y Matrices

Utilizando matrices y vectores, implementa un modelo del interferómetro Mach-Zehnder.
![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

### Rta

El estado final después de las puertas Hadamard y NOT en el interferómetro Mach-Zehnder es:

$$ \text{Estado final} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} $$

In [6]:
import numpy as np
# Defino las matrices y vectores a usar
H = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
x = np.array([[0, 1], [1, 0]])
q0 = np.array([[1], [0]])

# Aplico las transformaciones
paso_0 = np.dot(H, q0)
paso_1 = np.dot(x, paso_0)
paso_2 = np.dot(H, paso_1)

print("Estado final:")
print(paso_2)

Estado final:
[[1.]
 [0.]]


## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

### Rta
$$ M =  \frac{1}{\sqrt{2}}\begin{bmatrix} 0 \\ 0 \\ -1 \\ 1 \end{bmatrix}$$

In [7]:

array_a= np.array([[1/np.sqrt(2), (1/np.sqrt(2))], [(1/np.sqrt(2)), -1/np.sqrt(2)]])
s1 = np.array([[1],[0]]) 
s2 = np.array([[0],[1]])
array_uf = np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]])
array_b = np.array([[1,0], [0,1]])

A=np.kron (array_a,array_a) 
B=np.kron (s1, s2) 
C = np.dot (A,B) 
D = np.kron (array_a, array_b) 
E= np.dot (array_uf, C) 
print (np.dot (D, E)) 


[[ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [ 0.70710678]]
